Parameters:
  SubnetId:
    Description: The subnet on which the app will run within the selected VPC.
    Type: AWS::EC2::Subnet::Id
  RunnerEgressGroupId:
    Description: The security group for the runner instance that allows outbound traffic.
    Type: AWS::EC2::SecurityGroup::Id
  RunnerId:
    Type: String
    Description: The runner ID
  RunnerApiToken:
    Type: String
    Description: API token for the runner
  RunnerApiUrl:
    Type: String
    Description: API URL for the runner
    Default: https://runner.nuon.co
  InstanceType:
    Type: String
    Description: EC2 instance type for the runner
    Default: t3a.medium
    AllowedValues:
    - t3.small
    - t3.medium
    - t3a.small
    - t3a.medium
    - t3a.large
    - m5.large
    - m5a.large

Resources:
  RunnerASG:
    Properties:
      LaunchTemplate:
        LaunchTemplateId:
          Ref: RunnerLaunchTemplate
        Version:
          Fn::GetAtt:
          - RunnerLaunchTemplate
          - LatestVersionNumber
      MaxSize: "1"
      MinSize: "1"
      Tags:
      - Key: nuon_runner_id
        PropagateAtLaunch: false
        Value:
          Ref: RunnerId
      - Key: Name
        PropagateAtLaunch: false
        Value:
          Fn::Sub: ${AWS::StackName}-runner
      VPCZoneIdentifier:
      - Ref: SubnetId
    Type: AWS::AutoScaling::AutoScalingGroup

  RunnerInstanceProfile:
    Properties:
      InstanceProfileName:
        Fn::Sub: ${AWS::StackName}--runner-profile
      Roles:
      - Ref: RunnerInstanceRole
    Type: AWS::IAM::InstanceProfile

  RunnerInstanceRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
      Description: Instance role for the runner ec2 instance and ASG. Used to assume Provision, Deprovision, and Maintenance roles as needed by the app.
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - sts:AssumeIdentity
            Effect: Allow
            Resource: '*'
          Version: "2012-10-17"
        PolicyName: RunnerInstancePolicy
      - PolicyDocument:
          Statement:
          - Action: '*'
            Effect: Allow
            Resource: '*'
          Version: "2012-10-17"
        PolicyName: RunnerInstancePolicyAdmin
      Tags:
      - Key: nuon_runner_id
        Value:
          Ref: RunnerId
      - Key: Name
        Value:
          Fn::Sub: ${RunnerId}-runner-instance
    Type: AWS::IAM::Role

  RunnerLaunchTemplate:
    Properties:
      LaunchTemplateData:
        IamInstanceProfile:
          Name:
            Ref: RunnerInstanceProfile
        ImageId:
          Fn::Sub: '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}'
        InstanceType:
          Ref: InstanceType
        NetworkInterfaces:
        - AssociatePublicIpAddress: false
          DeleteOnTermination: true
          DeviceIndex: 0
          Groups:
          - Ref: RunnerEgressGroupId
          SubnetId:
            Ref: SubnetId
        TagSpecifications:
        - ResourceType: instance
          Tags:
          - Key: nuon_runner_id
            Value:
              Ref: RunnerId
          - Key: nuon_runner_api_url
            Value:
              Ref: RunnerApiUrl
          - Key: nuon_runner_api_token
            Value:
              Ref: RunnerApiToken
          - Key: nuon_runner_id
            Value:
              Ref: RunnerId
          - Key: Name
            Value:
              Fn::Sub: ${RunnerId}-runner-instance
        - ResourceType: network-interface
          Tags:
          - Key: nuon_runner_id
            Value:
              Ref: RunnerId
          - Key: Name
            Value:
              Fn::Sub: ${RunnerId}-runner-eni
        UserData:
          Fn::Base64: |
            #!/bin/bash
            curl https://raw.githubusercontent.com/nuonco/runner/refs/heads/main/scripts/aws/init.sh | bash
      LaunchTemplateName:
        Fn::Sub: ${AWS::StackName}-runner
    Type: AWS::EC2::LaunchTemplate

Outputs:
  ASG:
    Description: The runner ASG.
    Value: !Ref RunnerASG